### ISSUE TITLE
current version status?

### ISSUE THREAD

**Issue by dcsan** [Strngs/comet#15]
how's progress?
I cloned your repo/master and started using it, but can't seem to login...

is there a branch anywhere of the version that you put into atmosphere? I wanted to make a few mods to the last working version (there don't seem to be any tags/branches in this repo)

**Comment by WillHall** [comment]
Going well, working on configurination via UI.

I wasn't planning to tag/branch until 2.0 release

you can checkout and revert to https://github.com/Strngs/comet/tree/c5e19690e2a17f5fdb30369ea4e1ba5ccf00bb4e

for the version checked into atmosphere.

**Comment by WillHall** [comment]
Went ahead and tagged the version
https://github.com/Strngs/comet/releases
